apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../base/

patches:
  - patch: |-
      - op: replace
        path: /spec/destination
        value:
          server: "https://kubernetes.default.svc"
          namespace: dev
    target:
      kind: Application
  - patch: |-
      - op: replace
        path: /spec/template/spec/destination
        value:
          server: "https://kubernetes.default.svc"
          namespace: dev
    target:
      kind: ApplicationSet
