apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: default
spec:
  destination:
    namespace: default
  project: default
  source:
    path: app-set/base/applications/nginx
    repoURL: https://github.com/shubham-gann/argo-assignment.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    # automated:
    #   prune: true
    #   selfHeal: false